### ISSUE TITLE
Inconsistent daily volume on liquidity page and dxstats

### ISSUE THREAD

**Issue by niemam29** [ImpeccableHQ/swapr-dapp#1040]
**Description**
I've just noticed that the daily volume on Ethereum, Arbitrum and Gnosis is not the same as on the dxstats for most of the pairs.

#### Definition of done
- [X] Description is created (Task creator)
- [x] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Screenshots**
![cach2.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/f1bd81fe-53b8-4dc3-a3f7-58518b3097bb)![cache3.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/ba32537f-e4b1-446b-897a-9a58bbefc82c)

**Comment by Diogomartf** [comment]
**DxStats** 
[code repo](https://github.dev/SwaprDAO/swapr-info)

To show the volume in Pairs/List page it uses a hook to get the data: `usePairData(pairAddress)`

<img width="946" alt="image" src="https://user-images.githubusercontent.com/5664434/178964893-c20a825b-7243-4b41-8e73-4ecfa6241e3e.png">

In `usePairData`hook  it calls `getBulkPairData`

<img width="989" alt="image" src="https://user-images.githubusercontent.com/5664434/178965408-8204cc1e-a287-41f8-95fb-f3a071c51a7a.png">

This function does several things, it queries `PAIRS_BULK` and sets a `current` variable.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/5664434/178972068-8a376851-3b12-4a96-8cfe-e4e62257d752.png">

<img width="434" alt="image" src="https://user-images.githubusercontent.com/5664434/178972225-85b32593-1b0c-4a74-8290-451d1df409b9.png">

<img width="598" alt="image" src="https://user-images.githubusercontent.com/5664434/178971434-e6d220e3-0718-4a26-9761-e9bb33652870.png">

And it queries `PAIRS_HISTORICAL_BULK` and transforms the data with reduce.

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/5664434/178971970-cd400aab-a306-4955-bf24-d27467c96b41.png">

<img width="679" alt="image" src="https://user-images.githubusercontent.com/5664434/178970309-c877fe40-6ce3-4fbb-88d6-89c63f51a6a1.png">

if `PAIRS_HISTORICAL_BULK` query returns empty for _oneDayResult, twoDayResult, oneWeekResult_ it does a new query `PAIR_DATA` for each.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/5664434/178973332-fff20bbe-b93e-4d5a-95f0-e6f1ab4dd1b8.png">

<img width="834" alt="image" src="https://user-images.githubusercontent.com/5664434/178970640-1ab71370-e60a-4051-9c5e-e60068ecb76e.png">

It looks like those 3 queries, `PAIRS_HISTORICAL_BULK`, `PAIR_DATA`, `PAIRS_BULK` are using `volumeUSD` and not `dailyVolumeUSD`

At the end with all the data it calls a function `parseData`

<img width="932" alt="image" src="https://user-images.githubusercontent.com/5664434/178962221-536c74ba-a89b-46aa-8abc-ed9617ce5b22.png">

Which calls `get2DayPercentChange` that returns `oneDayVolumeUSD` which is used in PairsPage/PairsList

<img width="922" alt="image" src="https://user-images.githubusercontent.com/5664434/178962364-dd5eba23-3fe6-4bc6-bd23-0ec5bfb73773.png">

`oneDayVolumeUSD` is equal to 
`parseFloat(valueNow) - parseFloat(value24HoursAgo);`

---
**Swapr**
This is different that how it's done in Swapr.

It displays the `dailyVolumeUSD` almost right way from the subgraph query.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/5664434/178963350-2d6808a3-3ac2-495b-b828-c6c06e70c092.png">

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/5664434/178963292-1bc71c2f-9db3-490e-9a21-1048837c96e6.png">

 And then we use it like this:

` const { volume24hUSD } = usePair24hVolumeUSD(pair?.liquidityToken.address)`

**Comment by berteotti** [comment]
So I think dailyVolumeUSD is the volume corresponding a specific day. But we want to share the 24 hours volume, not the volume corresponding to this day (starting at midnight). In this regard, I think dxstats calculations are correct. We should compare the current volume and subtract the volume 24 hours ago to get the last 24 hours volume. 

So this seems to be, in dxstats code: `let currentChange = parseFloat(valueNow) - parseFloat(value24HoursAgo);`
