### ISSUE TITLE
Bridge transactions in Collect status are not displayed on the top of history

### ISSUE THREAD

**Issue by niemam29** [ImpeccableHQ/swapr-dapp#1491]
**Description**
Bridge transactions in Collect status are not displayed on the top of history

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Screenshots**
![image.png](https://images.zenhubusercontent.com/621e34c8aeddc379d59ee4d5/0848977a-5a58-45c5-92aa-2008e7cc511a)

**Comment by 0xVenky** [comment]
Cant repro anymore.
