### ISSUE TITLE
Alternative reciever doesn't work and crashes ui

### ISSUE THREAD

**Issue by Mi-Lan** [ImpeccableHQ/swapr-dapp#1602]

**Comment by MilanVojnovic95** [comment]
@Mi-Lan Tested and it works
https://gnosisscan.io/tx/0xe95c651e11887b0e84264575891d9a69db5393eb88a9cd04821776dd9a55ca87
can you write how to reproduce?

**Comment by Mi-Lan** [comment]
@MilanVojnovic95
1) Go on mainnet 
2) Select for example USDT to DAI
3) Add alternative receiver
![Screenshot 2022-12-07 at 18 37 48](https://user-images.githubusercontent.com/33226956/206252816-2f6d3347-6910-44a3-b5ce-8cab5a96db5d.png)
4)It just does normal swap 
![Screenshot 2022-12-07 at 18 38 21](https://user-images.githubusercontent.com/33226956/206252983-8787b506-a33b-40eb-bedd-99e3e3f8351e.png)

**Comment by Mi-Lan** [comment]
this time it didn't crash the ui but previous time it did

**Comment by Mi-Lan** [comment]
So I figured out the issue. Its related to how we handle passing receiver address to the sdk for certain trades namely the CurveTrade, UniswapTrade and ZeroXTrade. So @MilanVojnovic95 you were right it worked because it was probably routing through the either one of the uniswapV2 dexes or cowswap.

![Screenshot 2022-12-08 at 13 26 11](https://user-images.githubusercontent.com/33226956/206446036-f5eb405f-4256-4084-a9a0-065fe8946de8.png)

- The problem is that recipient is passed to the trade when it fetches quote so when you update it it will pull recipient that was there initially aka your address
- So the shitty approach would be to refetch the trades each time users changes reciever address which isn't the optimal solution but better one would be to add recipient argument to the swapTransaction function on rest of trades

![](https://media.tenor.com/67EGa-wMf5MAAAAC/sherlock-benedict-cumberbatch.gif)

**Comment by 0xVenky** [comment]
Fixed and released as part of Beta 18
