### ISSUE TITLE
Bridge claiming function infinite loop

### ISSUE THREAD

**Issue by KeenanLukeOM** [ImpeccableHQ/swapr-dapp#1626]
_Users are being sent back to the original chain from which a bridge transaction was executed when trying to execute a claim._

**Expected behaviour:** The claim function in the bridge tab sends the user to the correct chain and calls the claim function in the relevant bridge.

**Observed behaviour:** The claim function sends the user back to the initiated chain (possibly Eth mainnet?) and does nothing. This appears unrelated to the users' selected chain or bridge of choice, as reports have covered Ethereum mainnet, Gnosis Chain, Polygon, and Arbitrum. It also has encompassed several bridges from what I am able to tell at this time (Omnibridge, Connext, Arbitrum Native Bridge). 

**Collection of reports:**

<img width="580" alt="image" src="https://user-images.githubusercontent.com/76129769/207975805-afc23e3b-1411-4198-b4df-235d8ae617fd.png">

<img width="806" alt="image" src="https://user-images.githubusercontent.com/76129769/207976481-d66ceb4a-5201-48b0-8251-677da249d65b.png">

<img width="868" alt="image" src="https://user-images.githubusercontent.com/76129769/207976702-bda3ce99-e96b-4cd0-99d7-5466ab44f6d6.png">

<img width="371" alt="image" src="https://user-images.githubusercontent.com/76129769/207976565-f51726f9-5bf7-4379-b022-4a0998523075.png">

_Seems like a polygon to Arb transfer was pushing the user to mainnet as well?_

**A possibly related report from 09/29/2022:**

<img width="376" alt="image" src="https://user-images.githubusercontent.com/76129769/207976047-189b903b-f0bc-4c88-a65e-d13c18e52733.png">

_The user needed to visit the native bridge, although, stuck on pending, appears to be a separate, possibly solved issue compared to the above loop._

**Comment by 0xVenky** [comment]
Just my thoughts after a few tests and being there as part of feedbacks:

This doesnt seem to be very limited to Arbitrum. It kinda happens everywhere. If we use Connext / Socket, this is not a problem. This problem is a bit localised with Arbitrum bridge and Omnibridge. I will add more details here when I investigate more.
