### ISSUE TITLE
Token dropdown list on mobile is obscured by the keyboard.

### ISSUE THREAD

**Issue by whatt4** [ImpeccableHQ/swapr-dapp#1656]
User on Discord is saying they cannot use the token dropdown list on mobile because it is obscured by the keyboard.

"The only issue I have with it is when I want to trade the “scrollable token list” of tokens is covered up by the keyboard. I have to manually type in the token symbol and hit return for the token I want to trade to appear."

https://user-images.githubusercontent.com/120677298/210278601-bef3861a-e42a-45d1-9751-6c8a41313b21.mp4

**Test scenarios:**

Test on multiple screen sizes. Preferably from a small screen iphone 8 to a large iphone 14 Pro Max. The user should be able to pick the token he wants from the list and the list should not be hidden behind the keyboard completely.

**Comment by 0xVenky** [comment]
There is a new major change in token lists coming up shortly.

For the timebeing, we are fixing this by doing this: Hide the Common tokens when the user starts to type. This gives a bit more real estate from which the user can pick the token he is looking for.

**Comment by bejzik8** [comment]
And we are moving the modal to the top of the screen in order to create more space for the keyboard and avoid elements overlapping.
