### ISSUE TITLE
Does not show the real balance of funds on the wallet release: v1.0.0-beta.18

### ISSUE THREAD

**Issue by MilanVojnovic95** [ImpeccableHQ/swapr-dapp#1663]
**Description**
Constantly shows 0 balance of funds on the wallet.

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to 'Swapr page' (landing page)
2. Click on 'Connect wallet'
3. The true balance of "eth" funds (for example) should be displayed below the network logo and wallet address

**Screenshots**
Currently on release: v1.0.0-beta.18
![image](https://user-images.githubusercontent.com/57331244/210562829-7f68f1d5-a9b1-4336-b2ac-979caf5bdd86.png)

Currently on swapr.eth.link
![image](https://user-images.githubusercontent.com/57331244/210562615-45002163-1d70-472b-8aba-42223d7dd4b4.png)

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

**Comment by MilanVojnovic95** [comment]
Retested and the bug is still present, and can be reproduced.

**Comment by berteotti** [comment]
It's working for me, don't forget to use the same wallet in both setups.

**Comment by MilanVojnovic95** [comment]
Retested and it looks ok to me. 👍
