### ISSUE TITLE
Wrongly positioned Expeditions modal window

### ISSUE THREAD

**Issue by MilanVojnovic95** [ImpeccableHQ/swapr-dapp#1669]
**Description**

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to 'Swap' (Landing Page)
2. Click on 'Expeditions'
3. Modal window should be positioned like how it is on swapr.site and swapr.eth.link

**Expected behavior**
![image](https://user-images.githubusercontent.com/57331244/211262069-c23014ea-968a-4004-8f85-92b87afe83cc.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/57331244/211262123-00b85847-44fe-459c-a48f-be646db3cea8.png)

**Additional context**
Also, if it's relevant for the described byg, add information like the browser or OS.

**Comment by wixzi** [comment]
@MilanVojnovic95 Can you reproduce this now? When I tested it was working as expected.

**Comment by 0xVenky** [comment]
Solved in one of the earlier fixes
