### ISSUE TITLE
Fathom events - 18.1

### ISSUE THREAD

**Issue by 0xVenky** [ImpeccableHQ/swapr-dapp#1674]
- Trigger an event everytime user clicks Pro
- Trigger an event everytime user clicks Off
- Differentiate volume from market orders and limit orders for CoW
- Time spent on Pro mode? How many users spend more than 15 seconds, so everytime we refresh trade history, send an event with a counter. 
- How many times user updates Limit order price? And at what % above or below user places the limit order?

**Comment by adamazad** [comment]
Just summarizing:

We add a new type event type similar to `ecoRouter` volume metric, but named `proMode`, and then compare the volumes.
