### ISSUE TITLE
Switch tokens button error

### ISSUE THREAD

**Issue by MilanVojnovic95** [ImpeccableHQ/swapr-dapp#1716]
**Description**
When you click to exchange tokens from/to, it should really happen, but in this case set it so that both tokens are the same and it is not possible to perform a swap.

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to 'Swap' / landing page
2. Select any token
3. Try to switch a place from/to

**Screenshots**
[Swap _ error 03.02.webm](https://user-images.githubusercontent.com/57331244/216607955-26d71e43-fd30-46d0-9ffa-6735eab627e2.webm)

**Additional context**
More in screen video...

swapr.site 1.0.0-beta.18

**Comment by 0xVenky** [comment]
Closed as part of Beta 19
