### ISSUE TITLE
Rename left over WETH to ETH in pairs page

### ISSUE THREAD

**Issue by Mi-Lan** [ImpeccableHQ/swapr-dapp#416]
![Screenshot 2021-10-05 at 14 36 01](https://user-images.githubusercontent.com/33226956/136025495-7999d909-258c-4354-a30d-b7b8b75ef2b5.png)
![Screenshot 2021-10-05 at 14 35 54](https://user-images.githubusercontent.com/33226956/136025508-b8436b57-f725-4b9e-9800-c85235a5c705.png)
@luzzif What do you think? It may be a big confusing to have weth chosen and it displays eth in pairs...

**Comment by kingalg** [comment]
I know that you've opened this 2 months ago but I wanted to let you know that I saw it when doing first general check on the app and made a note that it can be confusing, especially for "beginner" users that we wouldn't want to scare away. So from tester perspective this issue make sense.

**Comment by MilanVojnovic95** [comment]
Retested and the bug is no longer present.
