### ISSUE TITLE
Bridge - update translations on navbar

### ISSUE THREAD

**Issue by karczuRF** [ImpeccableHQ/swapr-dapp#423]
Bridge link was added to navbar, can be seen as "Bridge". Translations for all languages is needed in public/locales/*.json files.
![image.png](https://images.zenhubusercontent.com/613b20acde2b3f0e5641fbb8/d1ee1d98-1070-405b-bc47-239c0f7f7ee7)

**Comment by MilanVojnovic95** [comment]
@denciu @karczuRF @0xVenky 
I just checked the specified file and I see that no changes have been made from this issue yet. Is there still work to be done?

**Comment by denciu** [comment]
Part of #562 therefore closing it.
