### ISSUE TITLE
Add support for tokens with `permit`

### ISSUE THREAD

**Issue by luzzif** [ImpeccableHQ/swapr-dapp#474]
The permit function (ERC 712) lets third party contract approve a token on the user's behalf, without the user itself submitting an approve transaction. The frontend should detect tokens implementing this function (such as 1INCH, UNI, ENS and other big ones) and act accordibgly.
For this to work, the router would most likely need to be upgraded (which is definitely possible) to account for functions that accept user signatures for approval purposes, and the frontend would need to ask the user to sign a typed message stating their intentions to approve the token to the router contract itself. The router would then call the `permit` function on the traded token passing in the signature, and the approval would be granted, sparing the user the separate approve transaction. 

USDC has permit function.
LINK does not have permit function.

**Comment by Dhaiwat10** [comment]
I'll be working on this

**Comment by kliyer-ai** [comment]
Relevant EIP: https://eips.ethereum.org/EIPS/eip-2612
This EIP might also be interesting as it accomplishes the same: https://eips.ethereum.org/EIPS/eip-3009

Currently both EIPs are still not final because they are being blocked by 712 but it seems like 712 might get finalized soon.

**Comment by kliyer-ai** [comment]
I had a discussion with William Schwab about this which was very helpful. He pointed me to the relevant files for Uniswap:

Sol: https://github.com/Uniswap/v3-periphery/blob/main/contracts/base/SelfPermit.sol
TS: https://github.com/Uniswap/interface/blob/main/src/hooks/useERC20Permit.ts

**Comment by 0xVenky** [comment]
Purging and cleaning up!
