### ISSUE TITLE
"View list" links for 2 token lists are not working

### ISSUE THREAD

**Issue by kingalg** [ImpeccableHQ/swapr-dapp#520]
Path: SWAP -> Select token -> Manage token lists

For the view that I've got there are 3 token lists. (Swapr token list, Compound and DXdao Carrot KPI tokens). For each of them there is an option "settings" that let you "view list" or "remove list". "View list" is a link redirecting the user to the new window that should show the list of mentioned tokens. Links for "Swapr token list" and "DXdao Carrot KPI tokens" shows empty page. 

![Screenshot 2021-12-16 at 15.33.31.png](https://images.zenhubusercontent.com/61b8ae8c4021b5ba7f93dbf2/fee4e36e-8f61-4ad2-9f3a-6cb83201b1ef)

This is what we expect to see (example from working link for "Compound" token list):
![Screenshot 2021-12-16 at 15.45.49.png](https://images.zenhubusercontent.com/61b8ae8c4021b5ba7f93dbf2/41003342-8905-4d5a-a6c6-7145696b070f)

And this is what we got for two other links:
![Screenshot 2021-12-16 at 15.46.15.png](https://images.zenhubusercontent.com/61b8ae8c4021b5ba7f93dbf2/f3a52e82-9e13-45a9-9362-0f54efd0c015)

**Comment by MilanVojnovic95** [comment]
Retested and the bug is still there.

**Comment by MilanVojnovic95** [comment]
Retested and the bug is still there.

**Comment by 0xVenky** [comment]
Purging and cleaning up! The token list currently is broken and have an issue #1700 created
