### ISSUE TITLE
Integrate Swapr in SimpleFi.finance

### ISSUE THREAD

**Issue by sacshin** [ImpeccableHQ/swapr-dapp#584]
https://docs.simplefi.finance/subgraph-development-documentation/dashboard-integration
https://github.com/SimpleFi-finance/subgraphs

![simplefi](https://user-images.githubusercontent.com/55705611/151244192-4a2fa415-8875-41fa-b1a9-53bbac178ecb.png)

**Comment by 0xVenky** [comment]
Closing this now! Almost a year gone, purging!
